### ISSUE TITLE
Help me to get atleast one can be anything except a static one RGB effects on my Gigabyte g5 mf laptop 

### ISSUE THREAD

**Issue by Manish8531** [DeviceIoControl/keyboard-colour-program#1]
Hey I am Manish8531 want to ask that can you please build a app that can control the keyboard light and also have animations in it I can assure you that our laptop hardware is capable just a software problem as no effect is availabel in the control centre of gigabyte g5 mf laptop this laptop is basically a rebranded clevo laptop  For this I can pay you This not only me asking you but there are hell lot of people who wants this.  Please help  I really have great hope on you.

**Comment by DeviceIoControl** [comment]
Hi Manish8531,

This repo is old and no longer being maintained. If you want help with this, please create an issue in the new repo:
https://github.com/DeviceIoControl/CppKeyboardColour 

Thanks

**Comment by Manish8531** [comment]
Issue created bro

**Comment by Manish8531** [comment]
Please help me I had great hope on you.
Please atleast help me to get one RGB effects it can be anything breathing colour cycle or just normal on and off feature means the keyboard light automatically one and off after every 3-5 seconds
I can pay for this
